name: my_template
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # For DeepLink
  app_links: ^6.3.2

  # For Image
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1

  # For Network
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.0.5

  # For Statemanagement
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.21.2

  # For Notification
  flutter_local_notifications: ^18.0.1

  # For UI
  cupertino_icons: ^1.0.8
  material_symbols_icons: ^4.2799.0
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  gap: ^3.0.1
  shimmer: ^3.0.0
  toastification: ^3.0.1

  # For Utils
  email_validator: ^3.0.0
  
  # For Router
  go_router: ^14.6.1

  # For Model
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # For System
  package_info_plus: ^8.0.2
  permission_handler: ^11.3.1

  # For Storage
  shared_preferences: ^2.3.2
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0

  # For Firebase
  # firebase_core: ^3.5.0
  # firebase_analytics: ^11.3.2
  # firebase_crashlytics: ^4.1.2
  firebase_messaging: ^15.1.2


dev_dependencies:
  build_runner: ^2.4.13

  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  
  # For testing
  mocktail: ^1.0.4

  # For model
  freezed: ^2.5.7
  json_serializable: ^6.9.0

  # For state management
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

  # For App
  change_app_package_name: ^1.4.0
  rename_app: ^1.6.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700



# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/logo.png"
#   min_sdk_android: 23
#   adaptive_icon_background: "#1c4214"
#   adaptive_icon_foreground: "assets/images/logo.png"
#   web:
#     generate: true
#     image_path: "assets/images/logo.png"



# dart run rename_app:main all="My App Name"
# dart run change_app_package_name:main com.new.package.name
# flutter pub get
# dart run flutter_launcher_icons